import{a as g,S as m,i as n}from"./assets/vendor-DDdXnYQq.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const p="51915811-ff4e89c2eae9a908c3a29b564",h="https://pixabay.com/api/",y=async s=>{const o={key:p,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0};try{const t=await g.get(h,{params:o});return t.data.hits.length===0?"Sorry, there are no images matching your search query. Please try again!":t.data.hits}catch(t){throw console.error("Error fetching images:",t),t}},L=new m(".gallery a",{captionsData:"alt",captionDelay:250}),l=document.querySelector(".gallery"),u=document.querySelector(".loader");function c(){l.innerHTML=""}function w(s){const o=s.map(({largeImageURL:t,webformatURL:a,tags:e,likes:r,views:i,comments:d,downloads:f})=>`
        <a class="gallery__link" href="${t}">
          <img class="gallery__image" src="${a}" alt="${e}" loading="lazy" />
          <div class="info">
            <p>Likes: ${r}</p>
            <p>Views: ${i}</p>
            <p>Comments: ${d}</p>
            <p>Downloads: ${f}</p>
          </div>
        </a>
      `).join("");l.insertAdjacentHTML("beforeend",o),L.refresh()}function S(){u.classList.remove("hidden")}function b(){u.classList.add("hidden")}const E=document.querySelector(".form");E.addEventListener("submit",async s=>{s.preventDefault();const o=s.target.elements["search-text"].value.trim();if(!o){n.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}try{S();const t=await y(o);typeof t=="string"?(n.error({title:"Error",message:t,position:"topRight"}),c()):(c(),w(t),n.success({title:"Success",message:`Found ${t.length} images`,position:"topRight"}))}catch(t){n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error("Error fetching images:",t)}finally{b()}});
//# sourceMappingURL=index.js.map
